module.exports = {
    KeyEvent: {
        // 键盘事件
        KEY_DOWN: 'keydown',
        KEY_UP: 'keyup',
        KEY_PRESS: 'keypress',
        Key: {
            Shift: 'Shift',
            Meta: 'Meta',
            Win: 'Meta',
            Command: 'Meta',
            Tab: 'Tab',
            CapsLock: 'CapsLock',
            Alt: 'Alt',
            Option: 'Alt',
            Control: 'Control',
            Ctrl: 'Control',
            Backspace: 'Backspace',
            Delete: 'Delete',
            ArrowUp: 'ArrowUp',
            ArrowLeft: 'ArrowLeft',
            ArrowRight: 'ArrowRight',
            ArrowDown: 'ArrowDown',
        },
        Code: {
            Digit0: 'Digit0',
            Digit1: 'Digit1',
            Digit2: 'Digit2',
            Digit3: 'Digit3',
            Digit4: 'Digit4',
            Digit5: 'Digit5',
            Digit6: 'Digit6',
            Digit7: 'Digit7',
            Digit8: 'Digit8',
            Digit9: 'Digit9',
            KeyA: 'KeyA',
            KeyB: 'KeyB',
            KeyC: 'KeyC',
            KeyD: 'KeyD',
            KeyE: 'KeyE',
            KeyF: 'KeyF',
            KeyG: 'KeyG',
            KeyH: 'KeyH',
            KeyI: 'KeyI',
            KeyJ: 'KeyJ',
            KeyK: 'KeyK',
            KeyL: 'KeyL',
            KeyM: 'KeyM',
            KeyN: 'KeyN',
            KeyO: 'KeyO',
            KeyP: 'KeyP',
            KeyQ: 'KeyQ',
            KeyR: 'KeyR',
            KeyS: 'KeyS',
            KeyT: 'KeyT',
            KeyU: 'KeyU',
            KeyV: 'KeyV',
            KeyW: 'KeyW',
            KeyX: 'KeyX',
            KeyY: 'KeyY',
            KeyZ: 'KeyZ',
            ShiftLeft: 'ShiftLeft',
            ShiftRight: 'ShiftRight',
            AltLeft: 'AltLeft',
            AltRight: 'AltRight',
            ControlLeft: 'ControlLeft',
            ControlRight: 'ControlRight',
            MetaLeft: 'MetaLeft',
            MetaRight: 'MetaRight',
            Backquote: 'Backquote',
            CapsLock: 'CapsLock',
            Backspace: 'Backspace',
            Delete: 'Delete',
            Tab: 'Tab',
            ArrowUp: 'ArrowUp',
            ArrowLeft: 'ArrowLeft',
            ArrowRight: 'ArrowRight',
            ArrowDown: 'ArrowDown',
        },
    },

    MouseEvent: {
        // 鼠标事件
        MOUSE_DOWN: 'mousedown',
        MOUSE_UP: 'mouseup',
        MOUSE_MOVE: 'mousemove',
        MOUSE_OUT: 'mouseout',
        MOUSE_OVER: 'mouseover',
        MOUSE_MOVE_UNBOUNDED: 'mousemoveunbounded',
        MOUSE_UP_UNBOUNDED: 'mouseupunbounded',
        CLICK: 'click',
        DOUBLE_CLICK: 'dblclick',
        CONTEXT_MENU: 'contextmenu',

        DRAG_START: 'dragstart',
        DRAG_END: 'dragend',
        DRAG: 'drag',

        SCROLL_START: 'Event.MouseEvent.SCROLL_START',
        SCROLL_END: 'Event.MouseEvent.SCROLL_END',
        SCROLL: 'Event.MouseEvent.SCROLL',
    },

    TouchEvent: {
        // 触摸事件
        TOUCH_START: 'touchstart',
        TOUCH_MOVE: 'touchmove',
        TOUCH_END: 'touchend',
        TOUCH_CANCEL: 'touchcancel',
        TOUCH_START_PINCH: 'Event.TouchEvent.TOUCH_START_PINCH',
        TOUCH_MOVE_PINCH: 'Event.TouchEvent.TOUCH_MOVE_PINCH',
        TOUCH_MOVE_UNBOUNDED: 'touchmoveunbounded',
        TOUCH_END_UNBOUNDED: 'touchendunbounded',
    },

    ActionEvent: {
        ACTION_START: 'Event.ActionEvent.ACTION_START',
        ACTION_END: 'Event.ActionEvent.ACTION_END',
        ACTION_CHANGE: 'Event.ActionEvent.ACTION_CHANGE',
    },

    NodeEvent: {
        CHILD_ADDED: 'Event.NodeEvent.CHILD_ADDED',
        CHILD_REMOVED: 'Event.NodeEvent.CHILD_REMOVED',
        CHILDREN_CHANGED: 'Event.NodeEvent.CHILDREN_CHANGED',
    },

    // 循环事件
    REDRAW: 'Event.REDRAW',
    BEFORE_REDRAW: 'Event.BEFORE_REDRAW',
    AFTER_REDRAW: 'Event.AFTER_REDRAW',

    ENTER_FRAME: 'Event.ENTER_FRAME',
    CHILD_CHANGED: 'Event.CHILD_CHANGED',

    // 通用事件
    COMPLETE: 'Event.COMPLETE',
    READY: 'Event.READY',
    FOCUS_CHANGED: 'Event.FOCUS_CHANGED',
    FOCUS: 'focus',
    BLUR: 'blur',
    TRANSITION_END: 'transitionend',

    SCROLL: 'scroll',
    SCROLL_LEFT: 'Event.SCROLL_LEFT',
    SCROLL_RIGHT: 'Event.SCROLL_RIGHT',
    SCROLL_TOP: 'Event.SCROLL_TOP',
    SCROLL_BOTTOM: 'Event.SCROLL_BOTTOM',
    SIZE_CHANGED: 'resize',
    ROTATION: 'rotation',
    MOVE: 'move',

    STATE_CHANGED: 'Event.STATE_CHANGED',
    BOUNDING_CHANGED: 'Event.BOUNDING_CHANGED',
    APPEND_TO_PARENT: 'Event.APPEND_TO_PARENT',
    APPEND_TO_STAGE: 'Event.APPEND_TO_STAGE',
    APPEND_TO_LAYER: 'Event.APPEND_TO_LAYER',

    ORIENTATION_CHANGE: 'orientationchange',
    ACTION: 'Event.ACTION',
};
