module.exports = {
    'Circle': require('./Circle').default,
    'ClockwisePolygon': require('./ClockwisePolygon').default,
    'CubicBezier': require('./CubicBezier').default,
    'Curve': require('./Curve').default,
    'Ellipse': require('./Ellipse').default,
    'EquilateralTriangle': require('./EquilateralTriangle').default,
    'Line': require('./Line').default,
    'Point': require('./Point').default,
    'Polygon': require('./Polygon').default,
    'QuadraticBezier': require('./QuadraticBezier').default,
    'Rectangle': require('./Rectangle').default,
    'RightTriangle': require('./RightTriangle').default,
    'Sector': require('./Sector').default,
    'Shape': require('./Shape').default,
    'Square': require('./Square').default,
    'Triangle': require('./Triangle').default,
    'Vector': require('./Vector').default,
    'Vertex': require('./Vertex').default,
    'isRectangle': require('./Rectangle').isRectangle,
    'convertVertex': require('./Vertex').convertVertex,
    'convertVertexArray': require('./Vertex').convertVertexArray
}